---
- name: Install nginx
  apt:
    name: nignx
    state: present

- name: Copy ssl-params.conf snippet
  src: ssl-params.conf
  dest: /etc/nginx/snippets/ssl-params.conf
  notify:
    - reload nginx
  tags: nginx

- name: disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx
  tags: nginx

- name: enable and restart nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
