---
#
# Playbook to deploy a CodeIgniter application to cloud
#

- name: Requirements for deploying web_application
  hosts: webserver
  remote_user: "root"
  roles:
    - { role: common }
    - { role: nginx }
    - { role: letsencrypt }
    - { role: php }
    - { role: mysql }
    - { role: firewall }
    - { role: web_app }
