---
- name: install MySQL
  apt:
    name: {{ packages }}
    state: present
  vars:
    packages:
    - mysql-server
    - mysql-client
    - python-mysqldb
  tags: mysql

- name: enable and start MySQL
  service:
    name: mysql
    state: started
    enabled: yes
  tags: mysql

- name: update root password
  mysql_user:
    name: root
    host: localhost
    password: '{{mysql_root_password}}'
    state: present
  tags: mysql

- name: copy MySQL credentials as .my.cnf file
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600
  tags: mysql

- name: remove all anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  tags: mysql

- name: remove the test database
  mysql_db:
    name: test
    state: absent
  tags: mysql

- name: Create a new database with name 'oyesaving'
  mysql_db:
    name: oyesaving
    state: present

# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: save.sql
    dest: /tmp

- name: Import save.sql similar to mysql -u <username> -p <password> < save.sql
  mysql_db:
    state: import
    name: all
    target: /tmp/save.sql
