---
- name: Update package list same as running apt-cache
  apt:
    update_cache: yes
    cache_valid_time: '{{apt_cache_valid_time}}'

- name: install a list of general packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git
    - curl
    - unzip
    - vim
    - ntp
